kind: Namespace
apiVersion: v1
metadata:
  name: servicenow
  labels:
    name: servicenow
---
apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: mid-rofs-deployment
  namespace: servicenow 
spec: 
  selector: 
    matchLabels: 
      app: mid 
  replicas: 1 
  template: 
    metadata: 
      labels: 
        app: mid 
      name: mid 
    spec: 
      containers:
        - name: mid-service 
          imagePullPolicy: Always 
          image: <image name>
          resources:
            requests:
              cpu: 50m
              memory: 300M
          securityContext:
            runAsUser: 101
            runAsGroup: 101
            allowPrivilegeEscalation: false
            privileged: false
            procMount: default
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
          env: 
            - name: MID_INSTANCE_URL 
              value: ""
            - name: MID_INSTANCE_USERNAME 
              value: "" 
            - name: MID_INSTANCE_PASSWORD 
              valueFrom:
               secretKeyRef:
                  name: mid-server-secret
                  key: SN_PASSWD
            - name: MID_SECRETS_FILE 
              value: "" 
            - name: MID_SERVER_NAME 
              value: ""
            - name: MID_PROXY_HOST 
              value: "" 
            - name: MID_PROXY_PORT 
              value: "" 
            - name: MID_PROXY_USERNAME 
              value: "" 
            - name: MID_PROXY_PASSWORD 
              value: "" 
            - name: MID_MUTUAL_AUTH_PEM_FILE 
              value: "" 
            - name: MID_WORKING_DIR
              value: "/emptyDir/snc_mid_server"
          volumeMounts:
          - mountPath: "/emptyDir/snc_mid_server"
            name: working-dir
      volumes:
      - name: working-dir
        emptyDir: {}
